# Generated by Django 4.2.13 on 2025-05-31 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم')),
                ('persian_name', models.CharField(blank=True, max_length=60, null=True, verbose_name='اسم فارسی')),
                ('country_id', models.CharField(blank=True, max_length=3, null=True, verbose_name='آیدی_کشور')),
                ('continent', models.CharField(blank=True, max_length=13, null=True, verbose_name='قاره')),
                ('population', models.IntegerField(blank=True, null=True, verbose_name='جمعیت')),
            ],
            options={
                'verbose_name': 'کشور',
                'verbose_name_plural': 'کشور ها',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس وب\u200cسایت')),
                ('isp', models.CharField(blank=True, max_length=200, null=True, verbose_name='ارائه دهنده خدمات')),
                ('org', models.CharField(blank=True, max_length=100, null=True, verbose_name='سازمان')),
                ('as_number', models.CharField(max_length=50, verbose_name='AS')),
                ('asname', models.CharField(max_length=100, verbose_name='AS Name')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='test.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'اپراتور',
                'verbose_name_plural': 'اپراتورها',
            },
        ),
        migrations.CreateModel(
            name='Isp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='اسم')),
                ('url', models.CharField(blank=True, max_length=30, null=True, verbose_name='آدرس')),
                ('cloud', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=18, null=True, verbose_name='وضعیت')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country', to='test.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'ارائه دهنده خدمات',
                'verbose_name_plural': 'ارائه دهندگان خدمات',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('manager', 'Manager'), ('admin', 'Admin'), ('user', 'User')], default='user', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
