# Generated by Django 4.2.13 on 2025-07-22 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(blank=True, max_length=100, null=True, verbose_name='سیستم\u200cعامل')),
                ('os_version', models.CharField(blank=True, max_length=50, null=True, verbose_name='نسخه سیستم\u200cعامل')),
                ('machine', models.CharField(blank=True, max_length=100, null=True, verbose_name='پردازنده / دستگاه')),
                ('browser', models.CharField(blank=True, max_length=100, null=True, verbose_name='مرورگر')),
                ('network_kind', models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع اتصال')),
                ('mac_address', models.CharField(blank=True, max_length=17, null=True, verbose_name='MAC آدرس')),
            ],
            options={
                'verbose_name': 'اطلاعات سیستم',
                'verbose_name_plural': 'اطلاعات سیستم ها',
            },
        ),
        migrations.CreateModel(
            name='Isp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=80, null=True, verbose_name='اسم')),
                ('url', models.CharField(blank=True, max_length=30, null=True, verbose_name='آدرس')),
                ('cloud', models.CharField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=18, null=True, verbose_name='وضعیت')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='country', to='setup.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'ارائه دهنده خدمات',
                'verbose_name_plural': 'ارائه دهندگان خدمات',
            },
        ),
        migrations.CreateModel(
            name='NetworkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'اطلاعات شبکه',
                'verbose_name_plural': 'اطلاعات شبکه ها',
            },
        ),
        migrations.CreateModel(
            name='ServerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='اسم')),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس وب\u200cسایت')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.country', verbose_name='کشور')),
                ('isp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='test.isp', verbose_name='ارائه دهنده خدمات')),
            ],
            options={
                'verbose_name': 'سرور تست',
                'verbose_name_plural': 'سرور های تست',
            },
        ),
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ping_avg', models.FloatField(blank=True, null=True, verbose_name='پینگ (ms)')),
                ('jitter', models.FloatField(blank=True, null=True, verbose_name='جیتر (ms)')),
                ('packet_loss', models.FloatField(blank=True, null=True, verbose_name='درصد از دست رفتن پکت')),
                ('speed_mbps', models.FloatField(blank=True, null=True, verbose_name='سرعت دانلود (Mbps)')),
                ('speed_MBps', models.FloatField(blank=True, null=True, verbose_name='سرعت دانلود (MB/s)')),
                ('loaded_size', models.FloatField(blank=True, null=True, verbose_name='اندازه فایل دانلود شده (MB)')),
                ('load_time', models.FloatField(blank=True, null=True, verbose_name='زمان دانلود (ثانیه)')),
                ('upload_speed_mbps', models.FloatField(blank=True, null=True, verbose_name='سرعت آپلود (Mbps)')),
                ('upload_time', models.FloatField(blank=True, null=True, verbose_name='زمان آپلود (ثانیه)')),
                ('upload_file_size', models.FloatField(blank=True, null=True, verbose_name='حجم فایل آپلودی (MB)')),
                ('latency', models.FloatField(blank=True, null=True, verbose_name='لَتِنسی')),
                ('test_state', models.CharField(blank=True, choices=[('success', 'موفق'), ('fail', 'ناموفق')], max_length=20, null=True, verbose_name='وضعیت تست')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ تست')),
                ('device_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test.deviceinfo', verbose_name='اطلاعات دستگاه')),
                ('network_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test.networkinfo', verbose_name='اطلاعات شبکه')),
                ('server_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test.servertest', verbose_name='سرور تست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تست سرعت',
                'verbose_name_plural': 'تست های سرعت',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس وب\u200cسایت')),
                ('isp', models.CharField(blank=True, max_length=200, null=True, verbose_name='ارائه دهنده خدمات')),
                ('org', models.CharField(blank=True, max_length=100, null=True, verbose_name='سازمان')),
                ('as_number', models.CharField(max_length=50, verbose_name='AS')),
                ('asname', models.CharField(max_length=100, verbose_name='AS Name')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.country', verbose_name='کشور')),
            ],
            options={
                'verbose_name': 'اپراتور',
                'verbose_name_plural': 'اپراتورها',
            },
        ),
        migrations.AddField(
            model_name='networkinfo',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='test.operator', verbose_name='اپراتور'),
        ),
    ]
