# Generated by Django 4.2.13 on 2025-08-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servertest',
            name='is_active',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=18, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='speedtest',
            name='server_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='test.servertest', verbose_name='سرور تست'),
        ),
    ]
