# Generated by Django 4.2.13 on 2025-08-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertest',
            name='is_active',
            field=models.BooleanField(blank=True, choices=[(True, 'فعال'), (False, 'غیر فعال')], default=None, max_length=18, null=True, verbose_name='وضعیت سرور'),
        ),
    ]
