# Generated by Django 4.2.13 on 2025-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinfo',
            name='province',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='استان'),
        ),
    ]
