# Generated by Django 4.2.13 on 2025-07-13 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
        ('test', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='اسم')),
                ('url', models.URLField(blank=True, null=True, verbose_name='آدرس وب\u200cسایت')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='setup.country', verbose_name='کشور')),
                ('isp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='test.isp', verbose_name='ارائه دهنده خدمات')),
            ],
            options={
                'verbose_name': 'سرور تست',
                'verbose_name_plural': 'سرور های تست',
            },
        ),
    ]
