# Generated by Django 4.2.13 on 2025-08-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_servertest_is_active_alter_speedtest_server_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isp',
            name='cloud',
            field=models.BooleanField(blank=True, choices=[('True', 'True'), ('False', 'False')], max_length=18, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='servertest',
            name='is_active',
            field=models.BooleanField(choices=[('True', 'True'), ('False', 'False')], default='True', max_length=18, verbose_name='وضعیت'),
        ),
    ]
