# Generated by Django 4.2.13 on 2025-08-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_alter_servertest_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='servertest',
            name='ip',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='آیپی'),
        ),
    ]
