# Generated by Django 4.2.13 on 2025-07-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_servertest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertest',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='اسم'),
        ),
        migrations.AlterField(
            model_name='servertest',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True, verbose_name='آدرس وب\u200cسایت'),
        ),
    ]
