# Generated by Django 4.2.13 on 2025-08-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0003_alter_isp_cloud_alter_servertest_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servertest',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'True'), (False, 'False')], default='True', max_length=18, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='speedtest',
            name='test_state',
            field=models.CharField(blank=True, choices=[(True, 'True'), (False, 'False')], max_length=20, null=True, verbose_name='وضعیت تست'),
        ),
    ]
