# Generated by Django 4.2.13 on 2025-08-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0006_alter_isp_cloud_alter_servertest_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speedtest',
            name='test_state',
            field=models.BooleanField(choices=[(True, 'موفق'), (False, 'ناموفق')], default=False, max_length=20, verbose_name='وضعیت تست'),
        ),
    ]
