# Generated by Django 4.2.13 on 2025-08-17 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0007_alter_speedtest_test_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speedtest',
            name='speed_MBps',
        ),
    ]
